version: '3.3'

networks:
  webnetwork:
    driver: bridge

volumes:
  prometheus_data:


services:
  prometheus:
    hostname: prometheus
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-admin-api"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1y"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - prometheus_data:/prometheus
    ports:
      - "30090:9090"
    links:
      - node-exporter
    networks:
      - webnetwork
  node-exporter:
    hostname: node-exporter
    image: bitnami/node-exporter
    ports:
      - "9100:9100"
    networks:
      - webnetwork


