version: '2'

services:
  grafana:
    image: bitnami/grafana
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "bitnami"
      GF_RENDERING_SERVER_URL: "http://grafana-image-renderer:8080/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
  grafana-image-renderer:
    image: bitnami/grafana-image-renderer
    ports:
      - '8080:8080'
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"
      ENABLE_METRICS: 'true'