pipeline {
    agent any

    tools {
        // Install the Maven version configured as "Maven3.9"  and add it to the path.
        maven "Maven3.9"
        jdk 'Corretto-17'
    }

    stages {
        stage('Build') {
            steps {

                // Run Maven on a Unix agent.
                sh "mvn clean install package"

            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.war'
                }
            }
        }

    }
}
